name: build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Setup npm
      uses: actions/setup-node@v4
      with:
        node-version: '18.19.1'

    - name: Set up Go 1.21+
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      id: go

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up tree-sitter v0.20.8+
      run: cargo install tree-sitter-cli

    - name: Install sass 1.58.0+
      run: npm install -g sass

    - name: Install eslint v8.56.0+
      run: npm install eslint eslint-config-standard

    - name: Install wasm-pack v0.12.1+
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'

    - name: List versions
      run: |
        rustc       --version
        tree-sitter --version
        wasm-pack   --version
        npx eslint  --version
        sass        --version
        go            version

    - name: Build
      run: make build-all
