name: build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
    - name: Setup NPM
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
      id: go

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install sass
      run: npm install -g sass

    - name: Install eslint
      run: npm install eslint eslint-config-standards
