name: build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Setup npm
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'

    - name: Set up Go 1.22+
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      id: go

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up tree-sitter v0.20.8+
      run: cargo install tree-sitter-cli

    - name: Install sass 1.58.0+
      run: npm install -g sass

    - name: Install eslint v8.56.0+
      run: npm install eslint eslint-config-standard

    - name: Install mocha, chai and web-tree-sitter
      run: |
        npm install mocha           --save-dev
        npm install chai            --save-dev
        npm install web-tree-sitter --save-dev

    - name: Install wasm-pack v0.12.1+
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

#   - name: Install wasm-pack v0.12.1+
#     run: cargo install wasm-pack

    - name: List versions
      run: |
        go version
        rustc       --version
        tree-sitter --version
        wasm-pack   --version
        sass        --version
        npx eslint  --version
        npx mocha   --version
        npx chai    --version
        npx web-tree-sitter --version

    - name: Build
      run: make build-all

    - name: Test
      run: |
        npm test

