name: nightly

on:
  workflow_dispatch:
  push:
    branches: [ "cloudflare" ]
  pull_request:
    branches: [ "cloudflare" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
    - name: Setup npm
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Go 1.21+
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
      id: go

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up tree-sitter v0.20.8+
      run: |
        cargo install tree-sitter-cli
        tree-sitter --version

    - name: Install sass 1.58.0+
      run: |
        npm install -g sass
        sass --version

    - name: Install eslint v8.56.0+
      run: |
        npm install eslint eslint-config-standard
        npx eslint --version

    - name: Install wasm-pack v0.12.1+
      run: |
        cargo install wasm-pack
        wasm-pack --version

    - name: Build
      run: make build-release

    - name: Upload Linux-x64 artifact
      uses: actions/upload-artifact@v3
      with:
        path: dist/linux/*
        name: vpd-0.0.0-linux

    - name: Upload MacOS-x64 artifact
      uses: actions/upload-artifact@v3
      with:
        path: dist/darwin/*
        name: vpd-0.0.0-darwin

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        path: dist/windows/*
        name: vpd-0.0.0-windows

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v3
      with:
        path: dist/html/*
        name: vpd-0.0.0-html
